name: Main Workflow

on:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.1

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and compile JAR
        run: mvn --batch-mode verify

      - name: Upload JAR file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api.jar
          path: target/api.jar

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: api.jar

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version
          heroku plugins:install java

      - name: Authenticate on Heroku
        run: heroku authorizations:create

      - name: Deploy the JAR
        run: heroku deploy:jar api.jar --app et-github-actions-demo
